# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# A snapshot resolver dictates the compiler version and the set of packages
# to be used for project dependencies. For example:
#
# resolver: lts-3.5
# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
# resolver: ghcjs-0.1.0_ghc-7.10.2
# resolver:
#  name: custom-snapshot
#  location: "./custom-snapshot.yaml"
resolver: nightly-2017-07-31

compiler: ghc-8.2.1

# A package marked 'extra-dep: true' will only be built if demanded by a
# non-dependency (i.e. a user package), and its test suites and benchmarks
# will not be run. This is useful for tweaking upstream packages.
packages:
- '.'
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: [ adjunctions-4.3
            , async-2.1.1.1
            , attoparsec-0.13.1.0
            , base-orphans-0.6
            , base64-bytestring-1.0.0.1
            , bifunctors-5.4.2
            , binary-0.8.5.1
            , binary-strict-0.4.8.3
            , blaze-builder-0.4.0.2
            , bytes-0.15.3
            , bytestring-builder-0.10.8.1.0
            , Cabal-1.24.2.0
            , cabal-doctest-1.0.2
            , call-stack-0.1.0
            , case-insensitive-1.2.0.10
            , cereal-0.5.4.0
            , clock-0.7.2
            , comonad-5.0.1
            , containers-0.5.10.2
            , contravariant-1.4
            , cryptohash-md5-0.11.100.1
            , cryptohash-sha1-0.11.100.1
            , directory-1.3.1.1
            , distributive-0.5.2
            , entropy-0.3.8
            , exceptions-0.8.3
            , fail-4.9.0.0
            , free-4.12.4
            , hashable-1.2.6.1
            , HUnit-1.6.0.0
            , integer-logarithms-1.0.2
            , io-streams-1.4.0.0
            , io-streams-haproxy-1.0.0.1
            , kan-extensions-5.0.2
            , lens-4.15.4
            , lifted-base-0.2.3.11
            , linear-1.20.7
            , monad-control-1.0.2.2
            , mtl-2.2.1
            , network-2.6.3.2
            , network-info-0.2.0.8
            , network-uri-2.6.1.0
            , old-locale-1.0.0.7
            , parallel-3.2.1.1
            , parsec-3.1.11
            , prelude-extras-0.4.0.3
            , primitive-0.6.2.0
            , process-1.4.3.0
            , profunctors-5.2.1
            , random-1.1
            , readable-0.3.1
            , reflection-2.1.2
            , regex-base-0.93.2
            , regex-posix-0.95.2
            , scientific-0.3.5.1
            , semigroupoids-5.2.1
            , semigroups-0.18.3
            , SHA-1.6.4.2
            , snap-core-1.0.2.1
            , snap-server-1.0.2.2
            , StateVar-1.1.0.4
            , stm-2.4.4.1
            , streaming-commons-0.1.18
            , tagged-0.8.5
            , text-1.2.2.2
            , th-abstraction-0.2.3.0
            , time-1.6.0.1
            , transformers-base-0.4.4
            , transformers-compat-0.5.1.4
            , unix-2.7.2.2
            , unix-compat-0.4.3.1
            , unordered-containers-0.2.8.0
            , uuid-1.3.13
            , uuid-types-1.0.3
            , vector-0.12.0.1
            , void-0.7.2
            , websockets-0.12.2.0
            , websockets-snap-0.10.2.3
            , zlib-0.6.1.2
            , zlib-bindings-0.1.1.5
            ]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.4"

# Override the architecture used by stack, especially useful on Windows
arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor

# Rebuild a package when its GHC options change
rebuild-ghc-options: true

ghc-options:
    # All packages
    "*": '-O2 -funbox-strict-fields -threaded -rtsopts "-with-rtsopts=-N" -Wall -fprint-unicode-syntax -fwarn-tabs'

# Packages that ghc-options applies to
apply-ghc-options: targets # All local packages that are targets
